version: "3.7"

services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: flightplanner
      POSTGRES_USER: flightplanner
      POSTGRES_DB: flightplanner
